### ISSUE TITLE
how can i access methods like Mutex?

### ISSUE THREAD

**Issue by xsteadfastx** [tonglil/buflogr#7]
```
var buf bytes.Buffer
log := buflogr.NewWithBuffer(&buf)

underlier := log.GetSink()(buflogr.Underlier)
```
throws an invalid operation error.

**Comment by tonglil** [comment]
There's a typo, missing the type assertion on `GetSink()`:
`underlier := log.GetSink().(buflogr.Underlier)`

Take a look here: https://go.dev/play/p/rgmgQy5k67i

**Comment by xsteadfastx** [comment]
thank you :)
